### ISSUE TITLE
apakah masih bisa dipakai? atau harus upgrade menggunakan versi terbaru?

### ISSUE THREAD

**Issue by tossaro** [veritrans/vtweb-opencart#47]
saya pasang (sandbox) dapat error berikut : 
Veritrans Error (500): Sorry our system has experienced an internal error, we will fix it as soon as possible

**Comment by rizdaprasetya** [comment]
Halo,
Kami menyarankan anda menggunakan versi berikut:
https://github.com/veritrans/SNAP-opencart
Yang akan kami maintenance secara jangka panjang.

Terima kasih.

**Comment by tossaro** [comment]
ok, thank you
